CREATE DATABASE Datalake;

\c Datalake
-- CREAMOS TABLA EN BASE DE DATOS 
CREATE TABLE registro (
  Id SERIAL PRIMARY KEY,
  Tipo_operacion VARCHAR(40) NOT NULL,
  Fecha_registro DATE NOT NULL
);

-- CREAMOS TRIGGER
CREATE OR REPLACE FUNCTION after_insertar()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO registro (Tipo_operacion, Fecha_registro)
  VALUES ('INSERTE', CURRENT_DATE);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER after_insertar_trigger
AFTER INSERT ON extraccion
FOR EACH ROW
EXECUTE FUNCTION after_insertar();

--COMANDOS DE EXPLORACIÓN DE TABLAS.
SELECT * FROM extraccion;
SELECT * FROM registro;

-- COMANDOS PARA ELIMINACIÓN DE REGISTROS.
DELETE FROM extraccion;
DELETE FROM registro;

