# Utiliza la imagen oficial de Apache Airflow como base
FROM apache/airflow:2.3.3

# Copia tu archivo requirements.txt al contenedor
COPY requirements.txt /requirements.txt

# Instala las bibliotecas adicionales desde requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt




