CREATE DATABASE binance;
USE binance;

#CREAMOS UN REGISTRO PARA TOMAR ESOS DATOS CRUDOS DE LA TABLA "TABLA", ORDERNADORLOS Y VER SU FECHA DE INGRESO,ADEMAS DE AGREGAR UN IDENTIFICADOR (AUDITORIA).
CREATE TABLE `registro` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Tipo_operacion` VARCHAR(40) NOT NULL,
  `Fecha_registro` DATE NOT NULL,
  PRIMARY KEY (`Id`)
  );
  
#TRIGGER 
DELIMITER $$
CREATE TRIGGER after_insertar
AFTER INSERT ON tabla
FOR EACH ROW
BEGIN
  INSERT INTO registro (Tipo_operacion, Fecha_registro)
  VALUES ('INSERTE', CURDATE());
END$$

#COMANDOS EXPLORACION DE TABLAS.
SELECT * FROM tabla;
SELECT * FROM registro;

#COMANDOS PARA ELIMINAACION DE REGISTROS.
DELETE FROM tabla;
DELETE FROM registros;
